"""
Модуль парсинга G-code файлов.

Извлекает метаданные из G-code файлов различных слайсеров.
Приоритет: OrcaSlicer, с возможностью расширения на PrusaSlicer/Cura.
"""

import re
import os
import logging
from dataclasses import dataclass
from typing import Optional, List
from abc import ABC, abstractmethod

logger = logging.getLogger(__name__)

# Количество строк для чтения из начала и конца файла
HEADER_LINES = 100
TAIL_LINES = 600


@dataclass
class GCodeMetadata:
    """Результат парсинга G-code файла."""
    # Приоритетные поля
    estimated_time_seconds: Optional[float] = None
    filament_weight_grams: Optional[float] = None

    # Дополнительные поля
    layer_count: Optional[int] = None
    layer_height: Optional[float] = None
    nozzle_temp: Optional[int] = None
    bed_temp: Optional[int] = None
    slicer_name: Optional[str] = None
    slicer_version: Optional[str] = None
    filament_length_mm: Optional[float] = None
    filament_density: Optional[float] = None

    @property
    def estimated_time_minutes(self) -> Optional[float]:
        """Время в минутах для совместимости с моделью Task."""
        if self.estimated_time_seconds is not None:
            return round(self.estimated_time_seconds / 60, 2)
        return None

    def __repr__(self) -> str:
        return (
            f"GCodeMetadata(time={self.estimated_time_minutes}min, "
            f"filament={self.filament_weight_grams}g, "
            f"layers={self.layer_count}, slicer={self.slicer_name})"
        )


def parse_time_string(time_str: str) -> Optional[float]:
    """
    Парсит строку времени формата "1h 30m 45s", "2h 30m", "1m 8s".

    Args:
        time_str: Строка времени от слайсера

    Returns:
        Время в секундах или None если парсинг не удался
    """
    if not time_str:
        return None

    hours = minutes = seconds = 0

    # Ищем часы, минуты, секунды
    h_match = re.search(r'(\d+)\s*h', time_str, re.IGNORECASE)
    m_match = re.search(r'(\d+)\s*m(?!m)', time_str, re.IGNORECASE)  # m но не mm
    s_match = re.search(r'(\d+)\s*s', time_str, re.IGNORECASE)

    if h_match:
        hours = int(h_match.group(1))
    if m_match:
        minutes = int(m_match.group(1))
    if s_match:
        seconds = int(s_match.group(1))

    total = hours * 3600 + minutes * 60 + seconds
    return float(total) if total > 0 else None


class SlicerParser(ABC):
    """Базовый класс для парсеров разных слайсеров."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Название слайсера."""
        pass

    @abstractmethod
    def can_parse(self, content: str) -> bool:
        """Проверяет, подходит ли этот парсер для файла."""
        pass

    @abstractmethod
    def parse(self, header: str, tail: str) -> GCodeMetadata:
        """
        Парсит контент и возвращает метаданные.

        Args:
            header: Первые N строк файла
            tail: Последние M строк файла
        """
        pass


class OrcaSlicerParser(SlicerParser):
    """Парсер для OrcaSlicer (и BambuStudio, SuperSlicer)."""

    @property
    def name(self) -> str:
        return "OrcaSlicer"

    def can_parse(self, content: str) -> bool:
        """Проверяет сигнатуру OrcaSlicer в header."""
        patterns = [
            r"generated by OrcaSlicer",
            r"generated by BambuStudio",
            r"generated by SuperSlicer",
            r"generated by PrusaSlicer",
        ]
        for pattern in patterns:
            if re.search(pattern, content, re.IGNORECASE):
                return True
        return False

    def parse(self, header: str, tail: str) -> GCodeMetadata:
        """Парсит метаданные OrcaSlicer."""
        metadata = GCodeMetadata()

        # Извлекаем название и версию слайсера из header
        slicer_match = re.search(
            r"; generated by (\w+(?:\s*\w+)?)\s+([\d.]+)",
            header
        )
        if slicer_match:
            metadata.slicer_name = slicer_match.group(1).strip()
            metadata.slicer_version = slicer_match.group(2).strip()

        # Плотность филамента из header
        density_match = re.search(r"; filament_density:\s*([\d.]+)", header)
        if density_match:
            metadata.filament_density = float(density_match.group(1))

        # Количество слоёв из header или tail
        layers_match = re.search(r"; total layer(?:s)? (?:number|count)\s*[=:]\s*(\d+)", header + tail)
        if layers_match:
            metadata.layer_count = int(layers_match.group(1))

        # Время печати из tail (приоритет - normal mode)
        time_patterns = [
            r"; estimated printing time \(normal mode\)\s*=\s*(.+)",
            r"; total estimated printing time \(normal mode\)\s*=\s*(.+)",
            r"; estimated printing time\s*=\s*(.+)",
        ]
        for pattern in time_patterns:
            time_match = re.search(pattern, tail)
            if time_match:
                metadata.estimated_time_seconds = parse_time_string(time_match.group(1))
                if metadata.estimated_time_seconds:
                    break

        # Расход филамента в граммах из tail
        filament_g_match = re.search(r"; filament used \[g\]\s*=\s*([\d.]+)", tail)
        if filament_g_match:
            metadata.filament_weight_grams = float(filament_g_match.group(1))

        # Fallback: длина филамента в мм
        filament_mm_match = re.search(r"; filament used \[mm\]\s*=\s*([\d.]+)", tail)
        if filament_mm_match:
            metadata.filament_length_mm = float(filament_mm_match.group(1))

            # Если нет веса но есть длина и плотность - вычисляем
            if metadata.filament_weight_grams is None and metadata.filament_density:
                # Формула: масса = плотность * объём
                # Объём = pi * r^2 * длина (r = 1.75/2 = 0.875 мм)
                import math
                radius_mm = 1.75 / 2  # стандартный диаметр
                length_mm = metadata.filament_length_mm
                volume_mm3 = math.pi * (radius_mm ** 2) * length_mm
                volume_cm3 = volume_mm3 / 1000  # мм³ → см³
                metadata.filament_weight_grams = round(
                    metadata.filament_density * volume_cm3, 2
                )

        # Высота слоя из tail (CONFIG_BLOCK)
        layer_h_match = re.search(r"; layer_height\s*=\s*([\d.]+)", tail)
        if layer_h_match:
            metadata.layer_height = float(layer_h_match.group(1))

        # Температура сопла
        nozzle_match = re.search(r"; nozzle_temperature\s*=\s*(\d+)", tail)
        if nozzle_match:
            metadata.nozzle_temp = int(nozzle_match.group(1))

        # Температура стола
        bed_match = re.search(r"; hot_plate_temp\s*=\s*(\d+)", tail)
        if not bed_match:
            bed_match = re.search(r"; bed_temperature\s*=\s*(\d+)", tail)
        if bed_match:
            metadata.bed_temp = int(bed_match.group(1))

        return metadata


class CuraParser(SlicerParser):
    """Парсер для Ultimaker Cura."""

    @property
    def name(self) -> str:
        return "Cura"

    def can_parse(self, content: str) -> bool:
        return "Cura_SteamEngine" in content or "Generated with Cura" in content

    def parse(self, header: str, tail: str) -> GCodeMetadata:
        """Парсит метаданные Cura."""
        metadata = GCodeMetadata()
        content = header + tail

        # Версия слайсера
        slicer_match = re.search(r"Cura_SteamEngine\s+([\d.]+)", content)
        if slicer_match:
            metadata.slicer_name = "Cura"
            metadata.slicer_version = slicer_match.group(1)

        # Время печати в секундах (;TIME:5947)
        time_match = re.search(r";TIME:(\d+)", content)
        if time_match:
            metadata.estimated_time_seconds = float(time_match.group(1))

        # Филамент
        filament_match = re.search(r";Filament used:\s*([\d.]+)g", content)
        if filament_match:
            metadata.filament_weight_grams = float(filament_match.group(1))

        # Высота слоя
        layer_h_match = re.search(r";Layer height:\s*([\d.]+)", content)
        if layer_h_match:
            metadata.layer_height = float(layer_h_match.group(1))

        return metadata


def read_file_parts(file_path: str) -> tuple:
    """
    Читает начало и конец файла для парсинга.

    Args:
        file_path: Путь к G-code файлу

    Returns:
        Tuple (header, tail) - первые и последние строки файла
    """
    header_lines = []
    all_lines = []

    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for i, line in enumerate(f):
            if i < HEADER_LINES:
                header_lines.append(line)
            all_lines.append(line)

    header = ''.join(header_lines)
    tail = ''.join(all_lines[-TAIL_LINES:]) if len(all_lines) > TAIL_LINES else ''.join(all_lines)

    return header, tail


def parse_gcode_file(file_path: str) -> GCodeMetadata:
    """
    Парсит G-code файл и извлекает метаданные.

    Автоматически определяет слайсер и использует соответствующий парсер.
    При ошибке возвращает пустой объект GCodeMetadata.

    Args:
        file_path: Путь к G-code файлу

    Returns:
        GCodeMetadata с извлечёнными данными
    """
    metadata = GCodeMetadata()

    if not os.path.exists(file_path):
        logger.warning(f"G-code файл не найден: {file_path}")
        return metadata

    try:
        header, tail = read_file_parts(file_path)
    except (IOError, OSError) as e:
        logger.warning(f"Ошибка чтения G-code файла {file_path}: {e}")
        return metadata

    # Список парсеров в порядке приоритета
    parsers: List[SlicerParser] = [
        OrcaSlicerParser(),
        CuraParser(),
    ]

    # Пробуем каждый парсер
    for parser in parsers:
        if parser.can_parse(header):
            try:
                metadata = parser.parse(header, tail)
                logger.info(
                    f"G-code успешно распарсен ({parser.name}): "
                    f"время={metadata.estimated_time_minutes}мин, "
                    f"филамент={metadata.filament_weight_grams}г"
                )
                return metadata
            except Exception as e:
                logger.warning(f"Ошибка парсера {parser.name}: {e}")
                continue

    logger.warning(f"Не удалось определить слайсер для файла: {file_path}")
    return metadata


def estimate_print_parameters(file_path: str) -> tuple:
    """
    Парсит G-code файл и возвращает параметры печати.

    Совместимость с существующим API. Если парсинг не удался,
    использует fallback на размер файла.

    Args:
        file_path: Путь к G-code файлу

    Returns:
        Tuple (filament_grams, time_minutes)
    """
    metadata = parse_gcode_file(file_path)

    filament = metadata.filament_weight_grams
    time_minutes = metadata.estimated_time_minutes

    # Fallback на размер файла если данные не найдены
    if filament is None or time_minutes is None:
        try:
            size_kb = os.path.getsize(file_path) / 1024
        except OSError:
            size_kb = 0

        if filament is None:
            filament = round(5.0 + size_kb * 0.05, 2)
            logger.debug(f"Филамент: fallback на размер файла ({filament}г)")

        if time_minutes is None:
            time_minutes = round(30.0 + size_kb * 0.2, 1)
            logger.debug(f"Время: fallback на размер файла ({time_minutes}мин)")

    return round(filament, 2), round(time_minutes, 1)


# Для тестирования модуля напрямую
if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.DEBUG)

    if len(sys.argv) > 1:
        gcode_path = sys.argv[1]
    else:
        # Тестовый файл по умолчанию
        gcode_path = "Куб_PETG_1m8s.gcode"

    print(f"\nПарсинг файла: {gcode_path}")
    print("-" * 50)

    metadata = parse_gcode_file(gcode_path)

    print(f"Слайсер: {metadata.slicer_name} {metadata.slicer_version or ''}")
    print(f"Время печати: {metadata.estimated_time_minutes} мин ({metadata.estimated_time_seconds} сек)")
    print(f"Филамент: {metadata.filament_weight_grams} г")
    print(f"Слоёв: {metadata.layer_count}")
    print(f"Высота слоя: {metadata.layer_height} мм")
    print(f"Температура сопла: {metadata.nozzle_temp}°C")
    print(f"Температура стола: {metadata.bed_temp}°C")

    print("\n" + "-" * 50)
    filament, time = estimate_print_parameters(gcode_path)
    print(f"estimate_print_parameters(): filament={filament}г, time={time}мин")
