"""Тесты для backend/services/gcode_parser.py — парсинг G-code файлов."""
import pytest

from backend.services.gcode_parser import (
    GCodeMetadata,
    parse_time_string,
    parse_gcode_file,
    estimate_print_parameters,
)


class TestParseTimeString:
    """Парсинг строки времени от слайсера."""

    def test_full_hms(self):
        """Полный формат: часы, минуты, секунды."""
        result = parse_time_string("1h 30m 45s")
        assert result == 5445.0

    def test_minutes_only(self):
        """Только минуты."""
        result = parse_time_string("30m")
        assert result == 1800.0

    def test_hours_minutes(self):
        """Часы и минуты без секунд."""
        result = parse_time_string("2h 15m")
        assert result == 8100.0

    def test_invalid_string(self):
        """Некорректная строка — None."""
        result = parse_time_string("invalid")
        assert result is None


class TestParseOrcaSlicer:
    """Парсинг G-code от OrcaSlicer."""

    def test_orcaslicer_metadata(self, tmp_path):
        """OrcaSlicer: слайсер, время, филамент, слои."""
        gcode_file = tmp_path / "test_orca.gcode"
        gcode_file.write_text(
            "; generated by OrcaSlicer 2.0.0\n"
            "; filament_density: 1.24\n"
            "; total layer count = 100\n"
            "G28\n"
            "G1 X0 Y0 Z0.3\n"
            "; estimated printing time (normal mode) = 1h 30m\n"
            "; filament used [g] = 25.5\n"
            "; layer_height = 0.2\n"
            "; nozzle_temperature = 210\n"
            "; hot_plate_temp = 60\n"
        )
        metadata = parse_gcode_file(str(gcode_file))
        assert metadata.slicer_name == "OrcaSlicer"
        assert metadata.slicer_version == "2.0.0"
        assert metadata.filament_weight_grams == 25.5
        assert metadata.estimated_time_seconds == 5400.0
        assert metadata.layer_count == 100
        assert metadata.layer_height == 0.2
        assert metadata.nozzle_temp == 210
        assert metadata.bed_temp == 60


class TestParseCura:
    """Парсинг G-code от Cura."""

    def test_cura_metadata(self, tmp_path):
        """Cura: слайсер, время, филамент."""
        gcode_file = tmp_path / "test_cura.gcode"
        gcode_file.write_text(
            ";Generated with Cura_SteamEngine 5.4.0\n"
            ";TIME:5400\n"
            ";Filament used: 25.5g\n"
            ";Layer height: 0.2\n"
            "G28\n"
            "G1 X0 Y0 Z0.3\n"
        )
        metadata = parse_gcode_file(str(gcode_file))
        assert metadata.slicer_name == "Cura"
        assert metadata.slicer_version == "5.4.0"
        assert metadata.estimated_time_seconds == 5400.0
        assert metadata.filament_weight_grams == 25.5
        assert metadata.layer_height == 0.2


class TestParseUnknownSlicer:
    """Файл без маркеров слайсера."""

    def test_unknown_slicer_returns_empty_metadata(self, tmp_path):
        """Неизвестный слайсер — пустые метаданные."""
        gcode_file = tmp_path / "test_unknown.gcode"
        gcode_file.write_text("G28\nG1 X0 Y0 Z0.3\nG1 X100 Y100\n")
        metadata = parse_gcode_file(str(gcode_file))
        assert metadata.slicer_name is None
        assert metadata.filament_weight_grams is None
        assert metadata.estimated_time_seconds is None


class TestEstimatePrintParameters:
    """Функция estimate_print_parameters — fallback на размер файла."""

    def test_with_parsed_data(self, tmp_path):
        """С данными слайсера — возвращает распарсенные значения."""
        gcode_file = tmp_path / "test_est.gcode"
        gcode_file.write_text(
            "; generated by OrcaSlicer 2.0.0\n"
            "; estimated printing time (normal mode) = 1h 30m\n"
            "; filament used [g] = 25.5\n"
            "G28\n"
        )
        filament, time_min = estimate_print_parameters(str(gcode_file))
        assert filament == 25.5
        assert time_min == 90.0

    def test_fallback_on_unknown_slicer(self, tmp_path):
        """Без данных слайсера — fallback на размер файла."""
        gcode_file = tmp_path / "test_fallback.gcode"
        gcode_file.write_text("G28\nG1 X0 Y0 Z0.3\n")
        filament, time_min = estimate_print_parameters(str(gcode_file))
        # Fallback: filament = 5.0 + size_kb * 0.05, time = 30.0 + size_kb * 0.2
        assert filament > 0
        assert time_min > 0
